/*Questao1*/
SELECT COUNT(EXEMPLAR.CODLIVRO),
	   LIVRO.TITULO,
       LIVRO.ISBN
FROM exemplar
JOIN LIVRO ON EXEMPLAR.CODLIVRO = LIVRO.CODLIVRO
WHERE EXEMPLAR.SITUACAO = "disponível"
group by EXEMPLAR.CODLIVRO
;


/*Questao2*/
SELECT 
	Pessoa.nome,
    Pessoa.cpf,
    Pessoa.datanascimento
FROM PESSOA
JOIN
	ALUNO ON Aluno.codPessoa = pessoa.codPessoa
JOIN
	Professor ON Professor.codPessoa = pessoa.codPessoa
;

/*Questao3*/
SELECT avg(PROVAALUNO.NOTA) AS MEDIANOTAS,
		ALUNO.MATRICULA
FROM PROVAALUNO
JOIN PROVA ON PROVA.CODPROVA = PROVAALUNO.CODPROVA
JOIN ALUNO ON PROVA.CODPESSOA = ALUNO.CODPESSOA
where PROVAALUNO.NOTA > (PROVA.VALOR * 60) / 100 
GROUP BY PROVAALUNO.CODPESSOA
;


/*Questao4*/
SELECT avg(PROVAALUNO.NOTA ) AS MEDIAS,
		count(PROVAALUNO.codpessoa) as qtedAlunos,
        PESSOA.NOME,
        PROVA.DESCRICAO,
        PROVA.DATAAPLICACAO,
        PROVA.VALOR
        
FROM PROVAALUNO
JOIN PROVA ON PROVA.CODPROVA = PROVAALUNO.CODPROVA
JOIN PROFESSOR ON PROVA.CODPESSOA = PROFESSOR.CODPESSOA
JOIN PESSOA ON PESSOA.CODPESSOA = PROFESSOR.CODPESSOA
WHERE month(PROVA.DATAAPLICACAO) >6
GROUP BY PROVAALUNO.CODPROVA
;

/*Questao5*/
ALTER TABLE EMPRESTIMO ADD COLUMN QUANTIDADE NUMERIC(9,2);
UPDATE EMPRESTIMO
SET QUANTIDADE = day(EMPRESTIMO.DATADEVOLUCAO) - day(EMPRESTIMO.PRAZODEVOLUCAO)
WHERE EMPRESTIMO.DATADEVOLUCAO IS NOT NULL
;


/*Questao6*/
SELECT 
	EMPRESTIMO.DATARETIRADA,
    EMPRESTIMO.DATADEVOLUCAO,
    EMPRESTIMO.PRAZODEVOLUCAO,
    PESSOA.NOME,
    PESSOA.CPF,
    LIVRO.ISBN,
    LIVRO.TITULO
FROM EMPRESTIMO
JOIN PESSOA ON PESSOA.CODPESSOA = EMPRESTIMO.CODPESSOA
JOIN EXEMPLAR ON EMPRESTIMO.CODEXEMPLAR = EXEMPLAR.CODEXEMPLAR
JOIN LIVRO ON LIVRO.CODLIVRO = EXEMPLAR.CODLIVRO
WHERE EMPRESTIMO.DATADEVOLUCAO IS NOT NULL AND
	  EMPRESTIMO.DATADEVOLUCAO > EMPRESTIMO.PRAZODEVOLUCAO AND
      EMPRESTIMO.DATARETIRADA IS NOT NULL AND
      month(EMPRESTIMO.DATADEVOLUCAO) < 7
;
/*Questao7*/
SELECT PROVA.DESCRICAO AS PROVA,
	   PROVA.VALOR,
       PROVA.DATAAPLICACAO,
       PROVAALUNO.NOTA,
       ALUNO.MATRICULA,
       PESSOA.NOME AS ALUNO
FROM PROVAALUNO
JOIN PROVA ON PROVA.CODPROVA = PROVAALUNO.CODPROVA
JOIN ALUNO ON PROVAALUNO.CODPESSOA = ALUNO.CODPESSOA
JOIN PESSOA ON PESSOA.CODPESSOA = ALUNO.CODPESSOA
WHERE PROVAALUNO.NOTA > PROVA.VALOR or
	  PROVAALUNO.NOTA < 0
      
ORDER BY PROVA.DESCRICAO
;
